### PR TITLE
Use eslint-plugin-no-jquery/deprecated-3.5

### PR DESCRIPTION
**Pull request by edg2s**
Fix resulting warnings (event shorthands)

### CODE REVIEW

**Comment by edg2s** [comment]
Note that the `eslint-plugin-jquery` wasn't actually being used so has been removed.

**Comment by ateliee** [comment]
Your suggestion is splendid.
please fix lint.

**Comment by edg2s** [comment]
I'm not seeing any lint errors locally or in Travis. The error in Travis is:
`Error: Failed to replace env in config: ${NPM_TOKEN}`
Which sounds like a configuration problem.

**Comment by ateliee** [comment]
Unnecessary setting to deploy became the error by a problem.
I am making modifications in master branch now.
You dissolve conflict, and please do commit again.

However, the following error may occur.
```
Requires renaming 'node' to '$n' to avoid conflict with parent '$node'.
```

**Comment by edg2s** [comment]
Fixed?

**Review by ateliee — COMMENTED** [review]
Thank you!

**Review by ateliee — APPROVED** [review]
OK. I will merge this.

**Pull request merged**
